name: Server dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server # Default working directory for the job
    steps:
    - uses: actions/checkout@v4

    # --- server Build ---
    - run: pwd
    - run: rm -rf node_modules
    - run: rm -f package-lock.json
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: server
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
